/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAssured;

import org.junit.Test;

import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void teste(){
       when().
               get("https://viacep.com.br/ws/01001000/json/").
               then().statusCode(200)
               .body("gia",is("1004"));
    }
}
